services:
  - type: web
    name: data-cleaning-bot
    env: python
    runtime: python
    plan: free
    buildCommand: "pip install --no-build-isolation -r requirements.txt"
    startCommand: "uvicorn backend.main:app --host 0.0.0.0 --port 10000"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7   # <--- force Python version
